---
#Add location to the organization
- name: "Configure content | add location to organization"
  shell: "HOME=/root hammer location add-organization
    --name '{{ satellite_deployment_location  }}'
    --organization '{{ satellite_deployment_organization }}'"

- name: "Configure content | add default hostgroup"
  shell: "HOME=/root hammer hostgroup create
    --name default
    --content-view-id 1
    --organization '{{ satellite_deployment_organization }}'
    --locations '{{ satellite_deployment_location }}'
    --environment-id 1"
  ignore_errors: "yes" # yes I'm lazy

- name: "Configure content | add default activation key"
  shell: "HOME=/root hammer activation-key create
    --unlimited-hosts
    --organization '{{ satellite_deployment_organization }}'
    --lifecycle-environment-id 1
    --content-view-id 1
    --name auto_register"
  ignore_errors: "yes"

- name: "Configure content | add application lifecycle environment"
  shell: "HOME=/root hammer lifecycle-environment create
    --name '{{ item.name }}'
    --description '{{ satellite_deployment_organization }} {{ item.name }} environment'
    --prior '{{ item.prior }}'
    --organization '{{ satellite_deployment_organization }}'"
  with_items: "{{ satellite_deployment_lifecycle_environments }}"
  ignore_errors: "yes"

- name: "Configure content | create default content view"
  shell: "HOME=/root hammer content-view create
    --name default
    --description 'Default, unfiltered view of all content'
    --organization '{{ satellite_deployment_organization }}'"
  ignore_errors: yes

- include_tasks: _configure_content_repos_for_products.yml
  with_items:
    - "{{ satellite_deployment_repositories|map(attribute='product_name')|unique|list }}"
  loop_control:
    loop_var: product

# Why does red hat have to make this so difficult?
- name: "Configure content | promote content view to environment"
  shell: "HOME=/root hammer content-view version promote
    --content-view default
    --version 1
    --to-lifecycle-environment {{ item.name }}
    --organization '{{satellite_deployment_organization }}'"
  with_items: "{{ satellite_deployment_lifecycle_environments }}"
  tags:
    - "debug"
