---
- name: "Install satellite | Include answers vars"
  include_vars: "vars/answers.yml"
  tags:
  - "install_satellite"
  - "update_satellite"

# Check if service exist for foreman
- name: "Install satellite | check if service exist"
  stat:
    path: "/etc/init.d/foreman"
  register: "foreman_service_file"
  become: "yes"
  tags:
  - "install_satellite"
  - "update_satellite"

# Set the install command fact
- name: "Install satellite | Update satellite-installer command"
  set_fact:
    satellite_deployment_installer_cmd: "{{ satellite_deployment_installer_cmd
      }} --{{ item.key }}='{{ item.value }}'"
  with_dict: "{{ satellite_deployment_answers }}"
  tags:
  - "install_satellite"
  - "update_satellite"

# May look at section 3.3.3.2 of the 6.3 install guide and set up an answer file:
# https://access.redhat.com/documentation/en-us/red_hat_satellite/6.3/html/installation_guide/installing_satellite_server

# Make sure /var/lib/pulp and /var/cache/pulp are writable by non-root users
#- name: "Install satellite | Change perms on /var/cache/pulp"
#  file:
#    path: /var/cache/pulp
#    mode: "1477"

#- name: "Install satellite |Change perms on /var/lib/pulp"
#  file:
#    path: /var/lib/pulp
#    mode: "1477"

# Install satellite
- name: "Install satellite | Satellite {{ satellite_deployment_version }} installation"
  command: "{{ satellite_deployment_installer_cmd }}"
  become: "yes"
  when: foreman_service_file.stat.exists|bool == true
  tags:
  - "install_satellite"
  - "update_satellite"
