---
- name: "Install satellite | Include answers vars"
  include_vars: "vars/answers.yml"
  tags:
  - "install_satellite"
  - "update_satellite"

# Check if service exist for foreman
- name: "Install satellite | check if service exist"
  stat:
    path: "/etc/init.d/foreman"
  register: "foreman_service_file"
  become: "yes"
  tags:
  - "install_satellite"
  - "update_satellite"

# Just set the install command fact for 6.2
- name: "Install satellite | Update satellite-installer command"
  set_fact:
    satellite_deployment_installer_cmd: "{{ satellite_deployment_installer_cmd
      }} --{{ item.key }}='{{ item.value }}'"
  with_dict: "{{ satellite_deployment_answers }}"
  when: satellite_deployment_version|string == "6.2"
  tags:
  - "install_satellite"
  - "update_satellite"

#Run the install of Satellite 6.2
- name: "Install satellite | Satellite {{ satellite_deployment_version }} installation"
  command: "{{ satellite_deployment_installer_cmd }}"
  become: "yes"
  when: foreman_service_file.stat.exists|bool == true and satellite_deployment_version|string == "6.2"
  tags:
  - "install_satellite"
  - "update_satellite"
