---
#Copy the cert
- name: "SSL | copy CA cert from remote"
  become: "yes"
  get_url:
    url: "{{ satellite_ldap_ca_cert_url }}"
    dest: "{{ satellite_ldap_ca_cert_path }}"
  when: satellite_ldap_remote_ca_cert
  tags:
    - "ldap"

- name: "LDAP | copy CA cert"
  become: "yes"
  copy:
    src: "{{ satellite_ldap_ca_cert_path }}"
    dest: "{{ satellite_ldap_ca_cert_dest_path }}"
    mode: "0644"
    owner: "root"
  register: "ca_cert_file"
  tags:
    - "ldap"

- name: "LDAP | Get x509 hash from {{ satellite_ldap_ca_cert_dest_path }}"
  shell:
    cmd: "openssl x509 -noout -hash -in {{ satellite_ldap_ca_cert_dest_path }}"
  register: "ca_cert_hash"
  tags:
    - "ldap"

- name: "LDAP | Create a symlink to /etc/pki/tls/certs/{{ ca_cert_hash.stdout}}.0"
  file:
    path: "/etc/pki/tls/certs/{{ ca_cert_hash.stdout }}.0"
    state: link
    src: "{{ satellite_ldap_ca_cert_path }}"
  tags:
    - "ldap"

- name: "LDAP | Restart httpd"
  service:
    name: "httpd"
    state: restarted
  when: "ca_cert_file|changed"
  tags:
    - "ldap"

- name: "LDAP | setsebool nis_enabled on"
  seboolean:
    name: nis_enabled
    state: yes
    persistent: yes
  tags:
    - "ldap"

- name: "LDAP | create LDAP auth source"
  shell: "HOME=/root hammer auth-source ldap create 
    --server-type {{ satellite_ldap_server_type }}
    --host {{ satellite_ldap_host }}
    --port {{ satellite_ldap_port }}
    --tls {{ satellite_ldap_tls_enabled }}
    --base-dn {{ satellite_ldap_base_dn }}
    --ldap-filter {{ satellite_ldap_query_filter }}
    --attr-login {{ satellite_ldap_attr_login }}
    --onthefly-register false"
  tags:
    - "ldap"
