---
- include: set_facts.yml
- include: registration.yml
- include: network.yml
- include: firewall.yml
- include: install_software.yml
- include: install_satellite.yml
- include: configure_satellite.yml
- include: configure_capsule.yml
