---
# handlers file for juliovp01.ansible_satellite6

- name: "restart katello service"
  shell: "/usr/bin/katello-service restart"

- name: "restart httpd"
  service:
    name: httpd
    state: restarted
